---
- name: tunnelbroker reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: tunnelbroker restart
  ansible.builtin.systemd:
    name: tunnelbroker
    state: restarted
    enabled: true
  when: not tunnelbroker_role_debug|bool
